address: https://test-stand.gb.ru
sleep_time: 1
browser: firefox
wait: 5
login: Nikolai123
passwd: d1e074caeb
title: THE NEW POST CREATED BY SELENIUM
description: OMG! SELENIUM HERE!
content: THIS IS CONTENT POSTET BY SELENIUM!